In [31]:
import numpy as np

In [32]:
mylist = [1,2,3]

In [33]:
mylist

[1, 2, 3]

In [34]:
myarr = np.array(mylist)
myarr
type(myarr)


numpy.ndarray

In [35]:
myarr

array([1, 2, 3])

In [36]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [38]:
np.linspace(4,10,7)

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [40]:
np.random.rand(3,5)

array([[0.26865637, 0.91141491, 0.90174398, 0.0158578 , 0.85368225],
       [0.67560617, 0.03768029, 0.30894783, 0.56424949, 0.59407763],
       [0.68081341, 0.63243183, 0.93870249, 0.73711959, 0.74485551]])

In [41]:
np.random.randn(5,2)

array([[-0.01612325, -0.99077869],
       [ 4.42818738, -0.81846811],
       [-0.70074686,  1.21626929],
       [-0.18774099,  0.40337352],
       [-0.67567832,  0.07808226]])

In [42]:
np.random.seed(44)
arr = np.random.randint(0,101,5)
arr

array([20, 35, 45, 59,  3])

In [43]:
np.random.seed(44)
arr = np.random.randint(0,101,100)

In [44]:
arr

array([ 20,  35,  45,  59,   3,  96,  84,   3,  23,  55,  22,  89,  67,
        71,  67,  99, 100,  57,   1,  14,  36,  93,  85,  83,  96,  74,
        36,  31,  18,  72,  93,  61,  72,  74,  86,  16,  72,  51,  50,
        18,  92,  29,   1,  63,  12,   2,  75,  45,  66,  73,  56,  49,
         8,  36,  34,  10,  70,  53,  44,  21,  54,  50,  77,  59,  81,
        15,  92,  61,  81,  40,  74,  96,  99,  62,  25,  21,   0,  72,
        42,  80,   4,  78,  98,  31,  38,  22,  13,  94,  50,  69,  16,
         4,  98,  11,  40,  61,  91,  40,  36,  66])

In [45]:
arr.reshape(5,20)

array([[ 20,  35,  45,  59,   3,  96,  84,   3,  23,  55,  22,  89,  67,
         71,  67,  99, 100,  57,   1,  14],
       [ 36,  93,  85,  83,  96,  74,  36,  31,  18,  72,  93,  61,  72,
         74,  86,  16,  72,  51,  50,  18],
       [ 92,  29,   1,  63,  12,   2,  75,  45,  66,  73,  56,  49,   8,
         36,  34,  10,  70,  53,  44,  21],
       [ 54,  50,  77,  59,  81,  15,  92,  61,  81,  40,  74,  96,  99,
         62,  25,  21,   0,  72,  42,  80],
       [  4,  78,  98,  31,  38,  22,  13,  94,  50,  69,  16,   4,  98,
         11,  40,  61,  91,  40,  36,  66]])

In [46]:
arr = np.arange(0,11)

In [47]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [49]:
arr[0:5:2]

array([0, 2, 4])

In [52]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
sliced_array = arr[:5]
sliced_array

array([99, 99, 99, 99, 99])

In [57]:
sliced_array[:] = 99
sliced_array

array([99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [61]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr2d.shape

(3, 3)

In [66]:
arr2d[2,0]

7

In [68]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [74]:
arr = np.arange(0,21,2)
bool_arr = arr>4
arr[bool_arr]

array([ 6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [101]:
arr = arr+5
arr

array([5, 6, 7, 8, 9])

In [102]:
arr = arr-2
arr

array([3, 4, 5, 6, 7])

In [103]:
arr = arr + arr
arr

array([ 6,  8, 10, 12, 14])

In [86]:
arr = arr *arr

In [87]:
arr


array([ 36,  64, 100, 144, 196])

In [96]:
arr = arr - arr
arr

array([nan, nan, nan, nan, nan])

In [97]:
arr = 1/arr

In [98]:
arr

array([nan, nan, nan, nan, nan])

In [93]:
arr = 1/arr

In [94]:
arr

array([nan, nan, nan, nan, nan])

In [104]:
arr

array([ 6,  8, 10, 12, 14])

In [105]:
np.sqrt(arr)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162, 3.74165739])

In [106]:
arr

array([ 6,  8, 10, 12, 14])

In [107]:
arr.sum()

50

In [108]:
arr.mean()

10.0

In [109]:
arr.var()

8.0

In [110]:
arr.std()

2.8284271247461903

In [111]:
arr2d = np.arange(0,25).reshape(5,5)

In [112]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [113]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])